---
substitutions:
  gpio_led: GPIO2
  # For water one of: CCF, ft続, gal, L, m続
  # For better accuracy avoid using large units like CCF and m続.
  # You can always change the unit later in Home Assistant.
  volume_unit: 'm続'

packages:
  water_meter: !include
    file: esphome-magnetometer.yaml
    vars:
      device_class: 'water'
      device_icon: 'mdi:water'

switch:
  # LED flashes faster/slower as magnet rotates on water meter
  - platform: gpio
    id: led
    pin:
      number: ${gpio_led}
      inverted: true
